### ISSUE TITLE
added support for building libcidr.a :)

### ISSUE THREAD

**Issue by wsdookadr** [wikimedia-incubator/libcidr#1]
Hello Andrew,

I've just added static building of libcidr in the   **added_static_building_libcidr** branch.
This is in order for us to be able to build a completely independent udp-filters binary(this is in order for us
to easily test and develop our udp-filters tommorow, because building the udp-filters debian package takes a bit of time
and in order to take development time as close as possible to zero I consider a static build of udp-filters to be appropriate).

Please review this and perhaps merge it with the debian/   branch (of course as you know, you can ignore the GNUMakefile\* as they are automatically generated).

If review is succesful, please dpkg-buildpackage and upload the new packages to the debian repo.

Best regards,
Stefan

**UPDATE**: I've just built the udp-filters using libcidr.a , it produced a 1.2MB binary which works fine and we can
copy it around as we're testing stuff.

**Comment by ottomata** [comment]
Sounds good to me.  I'd say go ahead and merge this into the master branch.
